spawndelay = 50 #in frames

[red]
speed = 1
health = 1
src = """<circle cx=size cy=size r=size fill="red"/>"""
srcSize = 15
onDeath = []

[blue]
speed = 1.4
health = 2
src = """<circle cx=size cy=size r=size fill="blue"/>"""
srcSize = 16
onDeath = ["red"]

[green]
speed = 1.8
health = 3
src = """<circle cx=size cy=size r=size fill="green"/>"""
srcSize = 17
onDeath = ["blue"]

[yellow]
speed = 3.2
health = 4
src = """<circle cx=size cy=size r=size fill="yellow"/>"""
srcSize = 18
onDeath = ["green"]