[lane]
background = "images/..."
life = 50
gold = 1000

path = [
	[ # prettier-ignore
		[0, 150],
		["r", 150],
		["d", 150],
		["r", 150],
		["u", 100],
		["r", 150],
		["d", 150],
		["r", 100],
		["u", 287.5],
		["l", 300],
		["u", 20],
	],
]
