[lane]
background = "images/..."
life = 50
gold = 1000

path_start = [0, 150]
path = [
	# prettier-ignore
	["r", 150],
	["d", 100],
	["r", 150],
	["u", 100],
	["r", 150],
	["d", 150],
	["r", 100],
	["u", 300],
	["l", 325],
	["u", 50],
]
