[lane]
background = "images/..."
life = 50
gold = 1000
path = [
	[ # prettier-ignore
		[-50, 150],
		["r", 200],
		["d", 150],
		["r", 150],
		["u", 100],
		["r", 150],
		["d", 150],
		["r", 100],
		["u", 287.5],
		["l", 300],
		["u", 20],
	],
]
waves = [
	[
		"000",
	],
	[
		"1111001111",
	],
	[
		"1111002222",
	],
	[
		"22233322123",
	],
	[
		"33332223333",
	],
]
