[red]
src = "../images/bob.png"
magazine_size = 3
pellets = 1
spread = 40
fireDelay = 2
reloadTime = 50
range = 200
price = 200
[red.bullet]
power = 1
speed = 8
src = "<svg width=6 height=6><circle cx=3 cy=3 r=3 fill=white /></svg>"

[blue]
src = "../images/cannon.png"
magazine_size = 1
pellets = 1
spread = 0
fireDelay = 10
reloadTime = 180
price = 300
range = 165
[blue.bullet]
power = 10
speed = 5
src = "<svg width=16 height=16><circle cx=8 cy=8 r=8 fill=black /></svg>"

[aqua]
src = "../images/wizard.png"
magazine_size = 1
pellets = 1
spread = 10
fireDelay = 20
reloadTime = 40
price = 1000
range = 170
tail = 3 ## tba
[aqua.bullet]
power = 2
speed = 2 #7
src = "<svg width=6 height=6><circle cx=3 cy=3 r=3 fill=aqua /></svg>"

[pink]
src = "../images/speedy.png"
magazine_size = 1
pellets = 1
spread = 0.75
fireDelay = 7
reloadTime = 7
range = 75
price = 3000
[pink.bullet]
power = 1
speed = 10
src = "<svg width=6 height=6><circle cx=3 cy=3 r=3 fill=orange /></svg>"
