[red]
src = "../images/bob.png"
magazine_size = 2
pellets = 1
fireDelay = 10
reloadTime = 30
range = 150
[red.bullet]
power = 2
speed = 8
src = "<svg width=6 height=6><circle cx=3 cy=3 r=3 fill=white /></svg>"
