[red]
src = "../images/bob.png"
magazine_size = 2
pellets = 1
fireDelay = 3
reloadTime = 40
damage = 1
targetrange = 150
[red.bullet]
power = 2
speed = 5
src = "<svg width=6 height=6><circle cx=3 cy=3 r=3 fill=white /></svg>"
